# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ee92605b76ef87cbfa9b64de7190d6f4e0bafb402b05e22d8fd6bc2cdba9209c7f7048dfbf36c3588fe6a4e75f22aaa5ad494af077eda6cce6661b151f64d72

test:
  secret_key_base: e920cdfc0f23ed1e1e038867fb08b29b753604c85be76f1dc36b23e921191ee75593b354b3f6b73cae6f8c2795cdb6e60b51ed6a1527cafaa24f56b1932dc5be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
